#   -------------------------------------------------------------
#   Copyright (c) Henry Spatial Analysis. All rights reserved.
#   Licensed under the MIT License. See LICENSE in project root for information.
#   -------------------------------------------------------------

"""
Core functions for fitting Bayesian hierarchical models using JAX.
"""

from numpy.random import randint

import jax
import jax.numpy as jnp
import jax.random as jrd
import blackjax


def jax_rng():
    """
    Generate a JAX random key.
    """
    rng = jrd.PRNGKey(randint(2**32 - 1))
    return rng


def random_markov_chain(
    kernel: callable,
    init_state: blackjax.State,
    num_draws: int = 1_000,
    key: jrd.KeyArray | None = None
) -> blackjax.State:
    """
    Generate a Markov chain of samples from a BlackJAX kernel using JAX's scan.
    The Markov chain is generated by iteratively applying the kernel to the initial
    state. The samples are returned as a JAX array.

    Args:
        key: JAX random key.
        kernel: BlackJAX kernel.
        init_state: Initial state.
        num_draws: Number of draws to generate.
    """
    if key is None:
        key = jax_rng()
    @jax.jit
    def one_step(state, key):
        state, _ = kernel(key, state)
        return state, state
    keys = jrd.split(key = key, num = num_draws)
    _, states = jax.lax.scan(f = one_step, init = init_state, xs = keys)
    return states


def nuts_sample(
    log_density: callable,
    init_position: blackjax.State,
    num_draws: int = 1_000,
    key: jrd.KeyArray | None = None
) -> jnp.ndarray:
    """
    Generate samples from a BlackJAX kernel using NUTS.

    Args:
        key: JAX random key.
        log_density: Log density function.
        init_position: Initial position.
        num_draws: Number of draws to generate.
    """
    if key is None:
        key = jax_rng()
    init_key, warmup_key, sample_key = jrd.split(
        key = key,
        num = 3,
    )
    warmup = blackjax.window_adaptation(
        algorithm = blackjax.nuts,
        logdensity_fn = log_density,
    )
    (state, params), _ = warmup.run(
        rng_key = warmup_key,
        position = init_position,
        num_steps = num_draws,
    )
    kernel = blackjax.nuts(
        logdensity_fn = log_density,
        **params
    ).step
    states = random_markov_chain(
        key = sample_key,
        kernel = kernel,
        init_state = state,
        num_draws = num_draws,
    )
    param_draws = states.position
    return param_draws


def generate_predictive_draws(
    posterior_predictive: callable,
    param_draws: dict[str, jnp.ndarray],
    num_draws: int = 1_000,
    key: jrd.KeyArray | None = None,
) -> jnp.ndarray:
    """
    Generate predictive draws from a posterior distribution using JAX's vmap.

    Args:
        posterior_predictive: Posterior predictive function (data already incorporated)
        param_draws: Parameter draws.
        num_draws: Number of draws to generate.
        key: JAX random key.
    """
    if key is None:
        key = jax_rng()
    keys = jrd.split(key = key, num = num_draws)
    pred_draws = jax.vmap(
        fun = posterior_predictive,
        in_axes = (0, 0),
    )(keys, param_draws)
    return pred_draws.T
